apiVersion: v1
kind: Namespace
metadata:
  name: test-dev
---
apiVersion: v1
kind: Service
metadata:
  labels:
    service-type: external
  name: test
  namespace: test-dev
spec:
  clusterIP: None
  ports:
  - name: http
    port: 9080
    protocol: TCP
    targetPort: 9080
  type: ClusterIP